"""
RAG with Milvus Lite + MLX embeddings.

Each project gets its own DB file at {project_root}/.code-rag/milvus.db.
The HTTP server shares the MLX model across projects and caches Milvus clients per DB.
CLI and stdio MCP use ephemeral connections.

Full-text search via SQLite FTS5 sidecar for hybrid search (vector + keyword).
Results merged with Reciprocal Rank Fusion (RRF).
"""

import json
import os

# Block all HuggingFace network access at runtime.
# Models must be pre-downloaded via setup.sh / download-model.sh.
os.environ['HF_HUB_OFFLINE'] = '1'
os.environ['TRANSFORMERS_OFFLINE'] = '1'

from pymilvus import MilvusClient, DataType
from mlx_embeddings.utils import load as mlx_load, generate as mlx_generate
import mlx.core as mx
from contextlib import contextmanager
from pathlib import Path
from typing import List, Dict, Optional
import asyncio
import logging
import hashlib
import fnmatch
import yaml
import chunking  # Clean chunking utilities (no PyTorch/ChromaDB)
import nl_descriptions
from fts_hybrid import FTSIndex, rrf_merge

logger = logging.getLogger("code-rag.milvus")

# Embedding model configuration
# Default: SFR-Embedding-Code-2B_R (Gemma 2, 2304 dims). Also supports:
#   Qodo-Embed-1-1.5B (Qwen2, 1536 dims) via EMBED_MODEL_PATH env var.
# Prefers local Q8 quantized model over full-precision HF model.
_SCRIPT_DIR = Path(__file__).parent
_LOCAL_Q8_MODEL = _SCRIPT_DIR / "models" / "sfr-embed-code-2b-mlx-q8"
_DEFAULT_MODEL = str(_LOCAL_Q8_MODEL)
_MODEL_PATH = os.getenv("EMBED_MODEL_PATH", _DEFAULT_MODEL)
_EMBED_DIM = None  # Auto-detected from model config.json


def _detect_embed_dim(model_path: str) -> int:
    """Read hidden_size from the model's config.json to determine embedding dimension."""
    config_path = Path(model_path) / "config.json"
    if not config_path.exists():
        raise RuntimeError(f"Model config not found at {config_path}")
    with open(config_path) as f:
        config = json.load(f)
    dim = config.get("hidden_size")
    if not dim:
        raise RuntimeError(f"hidden_size not found in {config_path}")
    return dim


def _get_embed_dim() -> int:
    """Get embedding dimension, detecting from model config if needed."""
    global _EMBED_DIM
    if _EMBED_DIM is None:
        _EMBED_DIM = _detect_embed_dim(_MODEL_PATH)
    return _EMBED_DIM


def compute_file_hash(file_path: str) -> str:
    """Compute SHA256 hash of file content for change detection."""
    try:
        with open(file_path, 'rb') as f:
            return hashlib.sha256(f.read()).hexdigest()
    except Exception:
        return ""


def is_jaxb_generated(file_path: str) -> bool:
    """Check if a Java file is JAXB-generated by looking for the marker."""
    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            lines = [f.readline() for _ in range(50)]
            content = ''.join(lines)
            if 'schema fragment specifies the expected content' in content:
                return True
            if 'generated by the JavaTM Architecture for XML Binding' in content:
                return True
            if '@XmlRootElement' in content and '@XmlType' in content:
                return True
        return False
    except Exception:
        return False


# Configuration
COLLECTION_NAME = "codebase"

# Global MLX model (load once, reuse — this is the expensive resource)
_mlx_model = None
_mlx_tokenizer = None


def get_mlx_model():
    """Get or load MLX model (one-time load)."""
    global _mlx_model, _mlx_tokenizer, _EMBED_DIM

    if _mlx_model is not None:
        return _mlx_model, _mlx_tokenizer

    if not Path(_MODEL_PATH).exists():
        raise RuntimeError(
            f"Embedding model not found at {_MODEL_PATH}. "
            f"Run ./setup.sh or ./download-model.sh to download it."
        )

    _EMBED_DIM = _detect_embed_dim(_MODEL_PATH)
    model_name = Path(_MODEL_PATH).name
    print(f"Loading {model_name} from {_MODEL_PATH}...")
    _mlx_model, _mlx_tokenizer = mlx_load(_MODEL_PATH)
    print(f"{model_name} ready ({_EMBED_DIM} dims)")

    return _mlx_model, _mlx_tokenizer


# Query instruction prefix for models that require asymmetric encoding.
# SFR-Embedding-Code requires this on queries; documents are encoded raw.
# Qodo-Embed does not use instructions, so this is empty by default.
_QUERY_INSTRUCTION = None  # Auto-detected from model config


def _get_query_instruction() -> str:
    """Get the query instruction prefix, detecting from model config if needed."""
    global _QUERY_INSTRUCTION
    if _QUERY_INSTRUCTION is not None:
        return _QUERY_INSTRUCTION
    config_path = Path(_MODEL_PATH) / "config.json"
    if config_path.exists():
        with open(config_path) as f:
            config = json.load(f)
        # SFR/CodeXEmbed models use model_type "codexembed2b"
        if config.get("model_type", "").startswith("codexembed"):
            _QUERY_INSTRUCTION = "Instruct: Given Code or Text, retrieval relevant content\nQuery: "
            return _QUERY_INSTRUCTION
    _QUERY_INSTRUCTION = ""
    return _QUERY_INSTRUCTION


def embed_texts(texts: List[str]) -> List[List[float]]:
    """Embed texts (documents/passages) using MLX. No query instruction added."""
    model, tokenizer = get_mlx_model()
    output = mlx_generate(model, tokenizer, texts=texts)
    embeddings = output.text_embeds.tolist()
    mx.clear_cache()
    return embeddings


def embed_query(query: str) -> List[float]:
    """Embed a search query, prepending instruction prefix if the model requires it."""
    instruction = _get_query_instruction()
    text = f"{instruction}{query}" if instruction else query
    return embed_texts([text])[0]


# --- Client management ---

# Ephemeral session client (CLI batch indexing)
_active_client = None

# Persistent client cache: db_path -> MilvusClient (HTTP server)
_persistent_clients: Dict[str, MilvusClient] = {}
_fts = FTSIndex(
    "chunks_fts",
    ["path", "language", "type", "start_line", "end_line", "class_name", "component", "description"],
    indexed_metadata={"description"},
)

# Async concurrency primitives (initialized once for HTTP server)
_write_lock: Optional[asyncio.Lock] = None
_embed_semaphore: Optional[asyncio.Semaphore] = None
_server_mode = False


def init_server_mode():
    """Initialize async concurrency primitives for HTTP server mode.
    Persistent clients are created lazily per db_path."""
    global _write_lock, _embed_semaphore, _server_mode
    _write_lock = asyncio.Lock()
    _embed_semaphore = asyncio.Semaphore(1)
    _server_mode = True
    _fts.set_server_mode(True)
    print("Server mode initialized (persistent clients will be created per project)")


def close_server_mode():
    """Close all persistent clients (Milvus + FTS) and reset server mode."""
    global _write_lock, _embed_semaphore, _server_mode
    for path, client in list(_persistent_clients.items()):
        try:
            client.close()
            logger.info("Closed Milvus client: %s", path)
        except Exception as e:
            logger.warning("Error closing Milvus client %s: %s", path, e)
    _persistent_clients.clear()
    _fts.close_all()
    _write_lock = None
    _embed_semaphore = None
    _server_mode = False


def _get_persistent_client(db_path: str) -> MilvusClient:
    """Get or create a persistent client for the given DB path.
    On failure, evicts the stale client and retries once."""
    if db_path in _persistent_clients:
        try:
            _persistent_clients[db_path].has_collection(COLLECTION_NAME)
            return _persistent_clients[db_path]
        except Exception as e:
            logger.warning("Stale Milvus client for %s: %s — reconnecting", db_path, e)
            try:
                _persistent_clients[db_path].close()
            except Exception:
                pass
            del _persistent_clients[db_path]

    Path(db_path).parent.mkdir(parents=True, exist_ok=True)
    try:
        # Use relaxed gRPC keepalive to avoid milvus-lite GOAWAY/too_many_pings.
        # pymilvus defaults to 10s which overwhelms the embedded server over time.
        _persistent_clients[db_path] = MilvusClient(db_path, grpc_options={
            "grpc.keepalive_time_ms": 300_000,       # 5 min between pings (default 10s)
            "grpc.keepalive_timeout_ms": 10_000,      # 10s timeout for pong
            "grpc.keepalive_permit_without_calls": False,
        })
        logger.info("Opened persistent client: %s", db_path)
    except Exception as e:
        logger.error("Failed to connect to Milvus at %s: %s", db_path, e)
        raise
    return _persistent_clients[db_path]


def _write_model_config(meta_path: Path):
    """Write current model configuration metadata alongside the Milvus DB."""
    meta = {
        "embed_model_path": _MODEL_PATH,
        "embed_dim": _get_embed_dim(),
    }
    meta_path.parent.mkdir(parents=True, exist_ok=True)
    with open(meta_path, 'w') as f:
        json.dump(meta, f, indent=2)


def _check_model_consistency(db_path: str):
    """Check that current embedding model matches what was used to build the index.

    On first use, writes model_config.json. On subsequent loads, compares
    the stored embedding dimension against the current model and raises
    a clear error on mismatch.
    """
    meta_path = Path(db_path).parent / "model_config.json"
    current_dim = _get_embed_dim()

    if not meta_path.exists():
        _write_model_config(meta_path)
        return

    with open(meta_path) as f:
        stored = json.load(f)

    stored_dim = stored.get("embed_dim")
    if stored_dim and stored_dim != current_dim:
        stored_model = stored.get("embed_model_path", "unknown")
        raise RuntimeError(
            f"Embedding dimension mismatch: index was built with {stored_dim}-dim "
            f"embeddings (model: {stored_model}), but current model produces "
            f"{current_dim}-dim embeddings (model: {_MODEL_PATH}). "
            f"Re-index with: ./index.sh --force /path/to/project"
        )

    # Update model path if it changed but dim is the same
    if stored.get("embed_model_path") != _MODEL_PATH:
        _write_model_config(meta_path)


def _resolve_db_path(db_path: Optional[str]) -> str:
    """Resolve a db_path. Raises if not provided — every caller must supply one."""
    if not db_path:
        raise ValueError("db_path is required. Each project stores its index at {project}/.code-rag/milvus.db")
    return db_path


def _ensure_collection(client):
    """Create collection if it doesn't exist."""
    if not client.has_collection(COLLECTION_NAME):
        dim = _get_embed_dim()
        print(f"Creating Milvus collection: {COLLECTION_NAME} (dim={dim})")
        client.create_collection(
            collection_name=COLLECTION_NAME,
            dimension=dim,
            metric_type="COSINE",
        )
        print(f"Collection created: {COLLECTION_NAME}")


@contextmanager
def milvus_session(db_path: Optional[str] = None):
    """Open a long-lived session for batch operations (indexing).
    All milvus_client() calls within this context reuse the same connection.
    If server mode is active, reuses the persistent client."""
    global _active_client
    path = _resolve_db_path(db_path)

    if _server_mode:
        # HTTP server — reuse persistent client
        client = _get_persistent_client(path)
        _ensure_collection(client)
        _check_model_consistency(path)
        old_active = _active_client
        _active_client = client
        try:
            yield client
        finally:
            _active_client = old_active
    else:
        # CLI / stdio — open fresh connection
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        client = MilvusClient(path)
        _ensure_collection(client)
        _check_model_consistency(path)
        _active_client = client
        try:
            yield client
        finally:
            client.close()
            _active_client = None


@contextmanager
def milvus_client(db_path: Optional[str] = None):
    """Get a Milvus client.
    Priority: persistent client (server) > active session (batch) > fresh ephemeral."""
    global _active_client
    path = _resolve_db_path(db_path)

    if _server_mode:
        client = _get_persistent_client(path)
        _ensure_collection(client)
        _check_model_consistency(path)
        yield client  # Don't close — server lifetime
    elif _active_client is not None:
        yield _active_client  # Reuse session — don't close
    else:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        client = MilvusClient(path)
        _ensure_collection(client)
        _check_model_consistency(path)
        try:
            yield client
        finally:
            client.close()


# --- Core operations ---

def file_needs_indexing(file_path: str, db_path: Optional[str] = None) -> bool:
    """Check if file needs (re)indexing by comparing content hash."""
    abs_path = str(Path(file_path).absolute())
    current_hash = compute_file_hash(file_path)
    if not current_hash:
        return True

    try:
        with milvus_client(db_path) as client:
            results = client.query(
                collection_name=COLLECTION_NAME,
                filter=f'path == "{abs_path}"',
                limit=1,
                output_fields=["content_hash"]
            )
            if results and len(results) > 0:
                stored_hash = results[0].get('content_hash', '')
                if stored_hash == current_hash:
                    return False
            return True
    except Exception as e:
        logger.warning("file_needs_indexing check failed for %s: %s", abs_path, e)
        return True


def add_documents(documents: List[str], metadatas: List[Dict], ids: List[str],
                  content_hash: Optional[str] = None, db_path: Optional[str] = None,
                  documents_for_embed: Optional[List[str]] = None) -> int:
    """Add documents to Milvus with MLX embeddings.

    Args:
        documents_for_embed: If provided, these texts are embedded instead of documents,
            but the original documents are stored in the 'document' field. Used for
            augmented embedding (description + code) while storing only the code.
    """
    embeddings = embed_texts(documents_for_embed if documents_for_embed else documents)

    data = []
    for i, (doc, meta, doc_id, emb) in enumerate(zip(documents, metadatas, ids, embeddings)):
        int_id = hash(doc_id) & 0x7FFFFFFFFFFFFFFF

        doc_data = {
            "id": int_id,
            "vector": emb,
            "document": doc,
            "doc_id": doc_id,
            **meta
        }
        if content_hash:
            doc_data["content_hash"] = content_hash
        data.append(doc_data)

    with milvus_client(db_path) as client:
        client.insert(collection_name=COLLECTION_NAME, data=data)

    # Dual-write into FTS5 sidecar
    try:
        if db_path:
            fts_conn = _fts.connection(db_path)
            fts_records = [{
                "doc_id": doc_id,
                "content": doc,
                "path": meta.get("path", ""),
                "language": meta.get("language", ""),
                "type": meta.get("type", ""),
                "start_line": str(meta.get("start_line", "")),
                "end_line": str(meta.get("end_line", "")),
                "class_name": meta.get("class_name", ""),
                "component": meta.get("component", ""),
                "description": meta.get("description", ""),
            } for doc, meta, doc_id in zip(documents, metadatas, ids)]
            _fts.insert(fts_conn, fts_records)
            _fts.close_ephemeral(fts_conn)
    except Exception as e:
        logger.warning("FTS insert failed (non-fatal): %s", e)

    return len(documents)


def _content_fingerprint(content: str) -> str:
    """Fingerprint for dedup: normalize whitespace, first 500 chars."""
    return ' '.join(content.split())[:500]


def search(query: str, n: int = 5, type_filter: Optional[str] = None,
           language_filter: Optional[str] = None, db_path: Optional[str] = None) -> List[Dict]:
    """Hybrid search: vector similarity + FTS5 keyword search, merged with RRF."""
    fetch_n = n * 3

    # --- Vector search ---
    query_embedding = embed_query(query)

    filters = []
    if type_filter:
        filters.append(f'type == "{type_filter}"')
    if language_filter:
        filters.append(f'language == "{language_filter}"')
    filter_expr = " && ".join(filters) if filters else None

    with milvus_client(db_path) as client:
        results = client.search(
            collection_name=COLLECTION_NAME,
            data=[query_embedding],
            limit=fetch_n,
            filter=filter_expr,
            output_fields=["document", "path", "language", "type", "doc_id",
                           "description", "start_line", "end_line", "class_name", "component"]
        )

    vector_results = []
    if results and len(results) > 0:
        for hit in results[0]:
            entity = hit['entity']
            result = {
                'content': entity['document'],
                'doc_id': entity.get('doc_id', ''),
                'path': entity.get('path', ''),
                'language': entity.get('language', ''),
                'type': entity.get('type', ''),
                'distance': hit['distance'],
                'start_line': entity.get('start_line', 0),
                'end_line': entity.get('end_line', 0),
            }
            for field in ('description', 'class_name', 'component'):
                val = entity.get(field)
                if val:
                    result[field] = val
            vector_results.append(result)

    # --- FTS5 keyword search ---
    fts_filters = {}
    if type_filter:
        fts_filters["type"] = type_filter
    if language_filter:
        fts_filters["language"] = language_filter
    fts_results = _fts.search(query, n=fetch_n, filters=fts_filters or None, db_path=db_path)

    # --- Merge with RRF ---
    if fts_results and vector_results:
        merged = rrf_merge(vector_results, fts_results, n=fetch_n)
    elif fts_results:
        merged = fts_results
    else:
        merged = vector_results

    if not merged:
        return []

    # Deduplicate near-identical results (same code from different index entries)
    seen_fingerprints = set()
    deduped = []
    for r in merged:
        fp = _content_fingerprint(r.get('content', ''))
        if fp not in seen_fingerprints:
            seen_fingerprints.add(fp)
            deduped.append(r)
    merged = deduped

    # Take top n results
    final = merged[:n]

    # Clean up internal fields
    for r in final:
        r.pop("_rrf_score", None)
        r.pop("doc_id", None)

    return final


def delete_by_path(file_path: str, db_path: Optional[str] = None) -> int:
    """Delete all chunks for a given file path."""
    abs_path = str(Path(file_path).absolute())
    try:
        with milvus_client(db_path) as client:
            results = client.query(
                collection_name=COLLECTION_NAME,
                filter=f'path == "{abs_path}"',
                output_fields=["id"]
            )
            if results:
                client.delete(
                    collection_name=COLLECTION_NAME,
                    filter=f'path == "{abs_path}"'
                )
    except Exception as e:
        logger.warning("delete_by_path failed for %s: %s", abs_path, e)
        return 0

    # Also delete from FTS
    try:
        if db_path:
            conn = _fts.connection(db_path)
            _fts.delete(conn, "path", abs_path)
            _fts.close_ephemeral(conn)
    except Exception as e:
        logger.warning("FTS delete_by_path failed (non-fatal): %s", e)

    return len(results)


# Track which projects have had stale cleanup (once per server lifetime)
_stale_cleanup_done: set = set()


def cleanup_stale_entries(db_path: str):
    """Remove index entries for files that no longer exist on disk.
    Runs once per project per server lifetime."""
    project_root = str(Path(db_path).parent.parent)
    if project_root in _stale_cleanup_done:
        return
    _stale_cleanup_done.add(project_root)

    all_results = _query_all(["path"], db_path=db_path)
    unique_paths = set(r['path'] for r in all_results)

    removed = 0
    for path in unique_paths:
        if not os.path.exists(path):
            delete_by_path(path, db_path)
            removed += 1

    if removed:
        logger.info("Cleaned %d stale entries for %s", removed, Path(project_root).name)


def clear_collection(db_path: Optional[str] = None):
    """Clear all data (Milvus + FTS)."""
    with milvus_client(db_path) as client:
        if client.has_collection(COLLECTION_NAME):
            client.drop_collection(COLLECTION_NAME)
            print(f"Collection cleared")

    # Clear FTS database
    if db_path:
        _fts.clear(db_path)


def _query_all(output_fields: list, batch_size: int = 1000, db_path: Optional[str] = None) -> list:
    """Query rows from Milvus with offset pagination. Capped at 16384 by Milvus Lite."""
    MILVUS_MAX = 16384
    all_results = []
    offset = 0

    with milvus_client(db_path) as client:
        if not client.has_collection(COLLECTION_NAME):
            return []
        while offset < MILVUS_MAX:
            effective_limit = min(batch_size, MILVUS_MAX - offset)
            batch = client.query(
                collection_name=COLLECTION_NAME,
                filter="",
                limit=effective_limit,
                offset=offset,
                output_fields=output_fields
            )
            if not batch:
                break
            all_results.extend(batch)
            if len(batch) < effective_limit:
                break
            offset += effective_limit

    return all_results


def get_stats(db_path: Optional[str] = None) -> Dict:
    """Get index statistics. Uses row_count for totals, offset query for breakdowns."""
    with milvus_client(db_path) as client:
        if not client.has_collection(COLLECTION_NAME):
            return {'total_chunks': 0, 'total_files': 0, 'by_language': {}, 'by_type': {}}
        stats = client.get_collection_stats(COLLECTION_NAME)
    total_docs = stats['row_count']

    results = _query_all(["path", "language", "type"], db_path=db_path)
    unique_files = set(r['path'] for r in results)
    sampled = len(results) < total_docs

    by_language = {}
    for r in results:
        lang = r.get('language', 'unknown')
        by_language[lang] = by_language.get(lang, 0) + 1

    by_type = {}
    for r in results:
        t = r.get('type', 'unknown')
        by_type[t] = by_type.get(t, 0) + 1

    result = {
        'total_chunks': total_docs,
        'total_files': len(unique_files),
        'by_language': by_language,
        'by_type': by_type
    }
    if sampled:
        result['note'] = f'Stats based on {len(results)}/{total_docs} chunks (Milvus offset limit). File count is approximate.'
    return result


def list_indexed_files(db_path: Optional[str] = None) -> Dict:
    """List all indexed files grouped by type."""
    results = _query_all(["path", "type"], db_path=db_path)

    by_type = {}
    for r in results:
        file_type = r.get('type', 'unknown')
        path = r.get('path', '')
        if file_type not in by_type:
            by_type[file_type] = set()
        by_type[file_type].add(path)

    return {t: sorted(list(files)) for t, files in by_type.items()}


def add_file(path: str, force: bool = False, db_path: Optional[str] = None) -> int:
    """Add a file to Milvus (uses chunking for chunking)."""
    abs_path = str(Path(path).absolute())

    if not force and not file_needs_indexing(abs_path, db_path):
        return 0

    try:
        with milvus_client(db_path) as client:
            client.delete(collection_name=COLLECTION_NAME, filter=f'path == "{abs_path}"')
    except Exception as e:
        logger.warning("Pre-delete failed for %s (continuing): %s", abs_path, e)

    content_hash = compute_file_hash(path)
    chunks = chunking.chunk_file(path)
    if not chunks:
        return 0

    # Apply type_overrides from .ragconfig
    if db_path:
        _project_root = str(Path(db_path).parent.parent)
        type_overrides = load_ragconfig(_project_root).get('type_overrides', [])
        if type_overrides:
            rel_path = os.path.relpath(abs_path, _project_root)
            for override in type_overrides:
                if fnmatch.fnmatch(rel_path, override.get('pattern', '')):
                    for chunk in chunks:
                        chunk['type'] = override['type']
                    break

    # Generate NL descriptions if enabled (env var or descriptions.db exists)
    desc_enabled = nl_descriptions.is_enabled(db_path=db_path)
    descriptions = nl_descriptions.describe_chunks(chunks, db_path=db_path) if desc_enabled else [None] * len(chunks)

    docs = [c['content'] for c in chunks]

    # Build augmented docs for embedding (description prepended to code)
    docs_for_embed = []
    for c, desc in zip(chunks, descriptions):
        if desc:
            docs_for_embed.append(f"{desc}\n\n{c['content']}")
        else:
            docs_for_embed.append(c['content'])

    metas = [{
        'path': abs_path,
        'language': c['language'],
        'type': c['type'],
        'start_line': c.get('start_line', 0),
        'end_line': c.get('end_line', 0),
        'class_name': c.get('class_name', ''),
        'component': c.get('component', ''),
        **({"description": desc} if desc else {}),
    } for c, desc in zip(chunks, descriptions)]

    ids = [f"{abs_path}::{i}" for i in range(len(chunks))]

    add_documents(docs, metas, ids, content_hash=content_hash, db_path=db_path,
                  documents_for_embed=docs_for_embed if desc_enabled else None)

    return len(chunks)


def _get_indexed_paths_under(dir_path: str, db_path: Optional[str] = None) -> set:
    """Get all unique file paths in the index that start with dir_path."""
    try:
        with milvus_client(db_path) as client:
            if not client.has_collection(COLLECTION_NAME):
                return set()
            paths = set()
            escaped = dir_path.replace('"', '\\"')
            iterator = client.query_iterator(
                collection_name=COLLECTION_NAME,
                filter=f'path like "{escaped}%"',
                output_fields=["path"],
                batch_size=1000
            )
            while True:
                batch = iterator.next()
                if not batch:
                    break
                for r in batch:
                    paths.add(r['path'])
            iterator.close()
            return paths
    except Exception as e:
        logger.warning("_get_indexed_paths_under failed for %s: %s", dir_path, e)
        return set()


# Default excluded directories
_DEFAULT_EXCLUDED_DIRS = {'node_modules', 'build', 'dist', 'target', 'bin',
                          'test', 'tests', 'ext', 'bower_components',
                          '.sencha', 'locale', 'packages', 'sass',
                          'lib', 'libs', 'vendor', 'vendors',
                          'data', 'venv', 'cdk.out', 'generated'}


def _load_ragignore(project_root: Optional[str] = None) -> Optional[set]:
    """Load .ragignore from the project directory. Returns None if file doesn't exist."""
    if project_root:
        ragignore_path = Path(project_root) / '.ragignore'
    else:
        ragignore_path = Path(__file__).parent / '.ragignore'
    if not ragignore_path.exists():
        return None

    excluded = set()
    with open(ragignore_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                excluded.add(line)
    return excluded


def get_excluded_dirs(extra_excludes: Optional[List[str]] = None, project_root: Optional[str] = None) -> set:
    """Get the set of excluded directory names.
    Looks for .ragignore in project_root first, falls back to defaults."""
    ragignore = _load_ragignore(project_root)
    if ragignore is not None:
        excluded = ragignore
    else:
        excluded = set(_DEFAULT_EXCLUDED_DIRS)

    if extra_excludes:
        excluded.update(extra_excludes)

    return excluded


# --- Per-project .ragconfig ---

_ragconfig_cache: Dict[str, dict] = {}

_RAGCONFIG_DEFAULTS = {
    'min_relevance': 0.0,
    'exclude_extensions': [],
    'exclude_patterns': [],
    'type_overrides': [],
    'read_file_max_bytes': 102400,
}


def load_ragconfig(project_root: Optional[str] = None) -> dict:
    """Load .ragconfig from the project directory. Returns defaults for missing fields."""
    if not project_root:
        return dict(_RAGCONFIG_DEFAULTS)

    if project_root in _ragconfig_cache:
        return _ragconfig_cache[project_root]

    config_path = Path(project_root) / '.ragconfig'
    if not config_path.exists():
        _ragconfig_cache[project_root] = dict(_RAGCONFIG_DEFAULTS)
        return _ragconfig_cache[project_root]

    try:
        with open(config_path) as f:
            config = yaml.safe_load(f) or {}
    except Exception as e:
        logger.warning("Failed to load .ragconfig: %s", e)
        _ragconfig_cache[project_root] = dict(_RAGCONFIG_DEFAULTS)
        return _ragconfig_cache[project_root]

    result = dict(_RAGCONFIG_DEFAULTS)
    for key in _RAGCONFIG_DEFAULTS:
        if key in config:
            result[key] = config[key]
    _ragconfig_cache[project_root] = result
    logger.info("Loaded .ragconfig for %s", Path(project_root).name)
    return result


def invalidate_ragconfig(project_root: str):
    """Invalidate cached ragconfig for hot reload."""
    _ragconfig_cache.pop(project_root, None)


def index_directory(dir_path: str, extensions: Optional[List[str]] = None,
                    incremental: bool = True, progress_callback=None,
                    max_files: int = 0, extra_excludes: Optional[List[str]] = None,
                    jaxb_filter: bool = True, db_path: Optional[str] = None) -> Dict:
    """Index all files in a directory."""
    dir_path = Path(dir_path)
    extensions = extensions or ['.java', '.js', '.ts', '.tsx', '.jsx', '.json', '.xml', '.yaml', '.yml', '.md',
                                '.gradle', '.properties']

    # Derive project root from db_path ({root}/.code-rag/milvus.db) for .ragignore lookup
    project_root = str(Path(db_path).parent.parent) if db_path else None
    excluded_dirs = get_excluded_dirs(extra_excludes, project_root=project_root)
    ragconfig = load_ragconfig(project_root)
    ragconfig_exclude_ext = set(ragconfig.get('exclude_extensions', []))
    ragconfig_exclude_patterns = ragconfig.get('exclude_patterns', [])

    files_indexed = 0
    files_skipped = 0
    chunks_created = 0
    errors = 0
    by_language = {}
    by_type = {}

    # Collect files
    all_files = []
    for file_path in dir_path.rglob('*'):
        if not file_path.is_file():
            continue
        if file_path.suffix not in extensions:
            continue
        if any(part.startswith('.') for part in file_path.relative_to(dir_path).parts[:-1]):
            continue
        if excluded_dirs & set(file_path.parts):
            continue
        if file_path.suffix in ragconfig_exclude_ext:
            continue
        if ragconfig_exclude_patterns:
            rel = str(file_path.relative_to(dir_path))
            if any(fnmatch.fnmatch(rel, pat) for pat in ragconfig_exclude_patterns):
                continue
        if file_path.suffix in ('.js', '.jsx'):
            if file_path.with_suffix('.ts').exists() or file_path.with_suffix('.tsx').exists():
                continue
        if file_path.name.endswith('.d.ts'):
            continue
        if file_path.stat().st_size > 1024 * 1024:
            continue
        if file_path.name.startswith('.'):
            continue
        if jaxb_filter and file_path.suffix == '.java' and is_jaxb_generated(str(file_path)):
            continue
        all_files.append(file_path)

    if max_files > 0:
        all_files = all_files[:max_files]
    total_files = len(all_files)
    files_removed = 0

    disk_paths = {str(f.absolute()) for f in all_files}

    with milvus_session(db_path):
        if max_files == 0:
            indexed_paths = _get_indexed_paths_under(str(dir_path.absolute()), db_path)
            stale_paths = indexed_paths - disk_paths
            for stale_path in stale_paths:
                delete_by_path(stale_path, db_path)
                files_removed += 1
            if stale_paths:
                print(f"  Removed {len(stale_paths)} stale file(s) from index")

        for idx, file_path in enumerate(all_files):
            try:
                num_chunks = add_file(str(file_path), force=not incremental, db_path=db_path)
                if num_chunks > 0:
                    files_indexed += 1
                    chunks_created += num_chunks

                    lang = chunking.detect_language(str(file_path))
                    t = chunking.detect_type(str(file_path), lang)
                    by_language[lang] = by_language.get(lang, 0) + num_chunks
                    by_type[t] = by_type.get(t, 0) + num_chunks

                    if files_indexed % 10 == 0:
                        mx.clear_cache()
                else:
                    files_skipped += 1

            except Exception as e:
                print(f"Error indexing {file_path}: {e}")
                errors += 1

            if progress_callback:
                progress_callback(idx + 1, total_files, file_path.name)

    # Free description model memory after batch indexing
    if nl_descriptions.is_enabled(db_path=db_path):
        nl_descriptions.unload_model()

    return {
        'files_indexed': files_indexed,
        'files_skipped': files_skipped,
        'files_removed': files_removed,
        'chunks_created': chunks_created,
        'errors': errors,
        'by_language': by_language,
        'by_type': by_type,
    }


# --- Async wrappers (for HTTP server use) ---

async def search_async(query: str, n: int = 5, type_filter: Optional[str] = None,
                       language_filter: Optional[str] = None, db_path: Optional[str] = None) -> List[Dict]:
    """Async hybrid search. Serializes embedding via semaphore."""
    loop = asyncio.get_event_loop()

    if _embed_semaphore is not None:
        async with _embed_semaphore:
            return await loop.run_in_executor(
                None, lambda: search(query, n, type_filter, language_filter, db_path))
    else:
        return await loop.run_in_executor(
            None, lambda: search(query, n, type_filter, language_filter, db_path))


async def add_file_async(path: str, force: bool = False, db_path: Optional[str] = None) -> int:
    """Async add_file for use by file watcher. Uses embed semaphore + write lock."""
    loop = asyncio.get_event_loop()
    abs_path = str(Path(path).absolute())

    # Hash check is cheap — do it without locks
    if not force:
        needs = await loop.run_in_executor(None,
            lambda: file_needs_indexing(abs_path, db_path))
        if not needs:
            return 0

    # Embedding + DB write needs both semaphore and lock
    if _embed_semaphore is not None and _write_lock is not None:
        async with _embed_semaphore:
            async with _write_lock:
                return await loop.run_in_executor(None,
                    lambda: add_file(path, force=force, db_path=db_path))
    else:
        return await loop.run_in_executor(None,
            lambda: add_file(path, force=force, db_path=db_path))


async def delete_by_path_async(file_path: str, db_path: Optional[str] = None) -> int:
    """Async delete_by_path for use by file watcher. Uses write lock."""
    loop = asyncio.get_event_loop()

    if _write_lock is not None:
        async with _write_lock:
            return await loop.run_in_executor(None,
                lambda: delete_by_path(file_path, db_path))
    else:
        return await loop.run_in_executor(None,
            lambda: delete_by_path(file_path, db_path))
