import os
import tempfile
import unittest
from pathlib import Path

from tests import _env  # noqa: F401
from tests._env import write
from indexing_rules import IndexRules, looks_minified, DEFAULT_EXTENSIONS


class IndexRulesTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name).resolve()
        write(self.root / "src/main/java/App.java", "public class App { void run() {} }\n" * 5)
        write(self.root / "README.md", "# Readme\n\nsome docs\n")
        write(self.root / ".hidden/Secret.java", "class Secret {}\n" * 5)
        write(self.root / "custops/.nuxt/nitro.json", '{"a": 1}\n')
        write(self.root / "node_modules/pkg/index.js", "module.exports = 1;\n")
        write(self.root / "web/app.min.js", "var a=1;" * 10)
        write(self.root / "web/types.d.ts", "export type A = string;\n")
        write(self.root / "web/comp.ts", "export const x = 1;\n")
        write(self.root / "web/comp.js", "export const x = 1;\n")
        write(self.root / "web/plain.js", "export const y = 2;\n")
        write(self.root / "data/blob.json", '{"k": "' + "x" * 30000 + '"}\n')   # 'data' is excluded by default anyway
        write(self.root / "fixtures/blob.json", '{"k": "' + "x" * 30000 + '"}\n')
        write(self.root / "docs/private/notes.md", "private\n")
        write(self.root / "docs/public/guide.md", "public\n")
        write(self.root / ".ragconfig", "exclude_patterns:\n  - 'docs/private/*'\nexclude_extensions:\n  - .xml\n")
        write(self.root / "conf/app.xml", "<a/>\n")
        write(self.root / "gen/Jaxb.java",
              "//\n// This file was generated by the JavaTM Architecture for XML Binding\n" + "class Jaxb {}\n" * 5)
        self.rules = IndexRules(str(self.root))

    def tearDown(self):
        self.tmp.cleanup()

    def reason(self, rel):
        return self.rules.exclusion_reason(str(self.root / rel))

    def test_indexable_files(self):
        self.assertIsNone(self.reason("src/main/java/App.java"))
        self.assertIsNone(self.reason("README.md"))
        self.assertIsNone(self.reason("web/comp.ts"))
        self.assertIsNone(self.reason("web/plain.js"))
        self.assertIsNone(self.reason("docs/public/guide.md"))

    def test_hidden_directories_are_skipped(self):
        self.assertEqual(self.reason(".hidden/Secret.java"), "hidden path component")
        self.assertEqual(self.reason("custops/.nuxt/nitro.json"), "hidden path component")

    def test_excluded_dirs_and_extensions(self):
        self.assertEqual(self.reason("node_modules/pkg/index.js"), "excluded directory")
        self.assertEqual(self.reason("data/blob.json"), "excluded directory")
        self.assertEqual(self.reason("src/main/java/App.class"), "extension")

    def test_ragconfig_rules(self):
        self.assertEqual(self.reason("docs/private/notes.md"), "ragconfig exclude_patterns")
        self.assertEqual(self.reason("conf/app.xml"), "ragconfig exclude_extensions")

    def test_declaration_and_compiled_js(self):
        self.assertEqual(self.reason("web/types.d.ts"), "declaration file")
        self.assertEqual(self.reason("web/comp.js"), "compiled from typescript sibling")

    def test_minified_by_name_and_by_long_line(self):
        self.assertEqual(self.reason("web/app.min.js"), "minified")
        self.assertEqual(self.reason("fixtures/blob.json"), "minified")
        self.assertTrue(looks_minified("x/y/vendor.bundle.js", 10))
        self.assertFalse(looks_minified("x/y/App.java", 10))

    def test_jaxb(self):
        self.assertEqual(self.reason("gen/Jaxb.java"), "jaxb generated")
        self.assertIsNone(IndexRules(str(self.root), jaxb_filter=False).exclusion_reason(str(self.root / "gen/Jaxb.java")))

    def test_outside_root_and_missing(self):
        self.assertEqual(self.rules.exclusion_reason("/etc/passwd.java"), "outside project root")
        self.assertEqual(self.reason("src/nope.java"), "missing")
        # A deleted file that would have been indexable classifies as indexable when size is given
        self.assertIsNone(self.rules.exclusion_reason(str(self.root / "src/deleted.java"), size=0))

    def test_walk_matches_predicate(self):
        found = {os.path.relpath(p, self.root) for p in self.rules.walk()}
        self.assertEqual(found, {"src/main/java/App.java", "README.md", "web/comp.ts", "web/plain.js",
                                 "docs/public/guide.md"})
        under = {os.path.relpath(p, self.root) for p in self.rules.walk(str(self.root / "web"))}
        self.assertEqual(under, {"web/comp.ts", "web/plain.js"})

    def test_special_files(self):
        self.assertTrue(self.rules.is_config_file(str(self.root / ".ragconfig")))
        self.assertFalse(self.rules.is_config_file(str(self.root / "sub/.ragconfig")))
        self.assertTrue(self.rules.is_git_ref_file(str(self.root / ".git/HEAD")))
        self.assertFalse(self.rules.is_git_ref_file(str(self.root / "src/HEAD")))

    def test_reload_picks_up_config_changes(self):
        write(self.root / ".ragconfig", "exclude_patterns: []\n")
        self.assertEqual(self.reason("docs/private/notes.md"), "ragconfig exclude_patterns")  # cached
        self.rules.reload()
        self.assertIsNone(self.reason("docs/private/notes.md"))

    def test_ragignore_replaces_defaults(self):
        write(self.root / ".ragignore", "only_this\n")
        rules = IndexRules(str(self.root))
        self.assertIsNone(rules.exclusion_reason(str(self.root / "node_modules/pkg/index.js")))
        self.assertEqual(rules.excluded_dirs, {"only_this"})

    def test_default_extensions_include_schemas(self):
        for ext in (".graphql", ".proto", ".java", ".md"):
            self.assertIn(ext, DEFAULT_EXTENSIONS)


if __name__ == "__main__":
    unittest.main()
